name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install sqlalchemy
          pip install pytest
        
      - name: List directory contents for debugging
        run: ls -R

      - name: Make tests.sh executable
        run: chmod +x project/tests.sh
      
      - name: Run tests
        run: ./project/tests.sh
